### ISSUE TITLE
.azcli WebApp deploy script needs to check exit code for dotnet build and publish

### ISSUE THREAD

**Issue by snobu** [MS-GPS-Hackathons/MS-Identity-For-Apps-Hackathon#2]
https://github.com/MS-GPS-Hackathons/MS-Identity-For-Apps-Hackathon/blob/main/Student/Resources/Challenge_D1_03/DeployAppScriptB2B.azcli

^ This .azcli WebApp deploy script needs to check exit code for dotnet build and publish. It should not continue if there's an error as it can create multiple Web Apps in Azure for every failed run.

**Comment by fparpas** [comment]
Done
If build, publish or compress commands fail do not deploy app service to Azure
